apiVersion: v1
kind: Service
metadata:
  name: sentiment-api-svc
spec:
  selector:
    app: sentiment-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP  # Достаточно для port-forward